### ISSUE TITLE
Should Include migrations or not while pushing to github?

### ISSUE THREAD

**Issue by vaskrneup** [iamaakashbasnet/nepsevirt#23]
In several cases -- when there is multiple changes in db migrations files, there is usually issue while merging 2 sources as history doesn't match.

- it doesn't show up until the problem gets really large.
-  lets not push migrations to the repo, keep the current migrations or remove it completely.
-  user can run their migrations when they clone the project
- it safe guards db from unintended corruption

we can finalize the changes after discussion -- for now i am not pushing migrations in username-email-support branch

**Comment by iamaakashbasnet** [comment]
Let's leave it now.
